version: '3.8'

services:

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis

  backend:
    image: hello-backend
    #ports:
    #  - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: backend
    depends_on:
      - redis
      - postgres

  frontend:
    image: hello-frontend
    #ports:
    #  - "5000:5000"
    container_name: frontend

  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    depends_on:
      - frontend
      - backend

volumes:
  postgres-data: