version: '3.8'

services:
  redis:
    image: redis
    container_name: redis

  backend:
    image: hello-backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    container_name: backend-redis

  frontend:
    image: hello-frontend
    ports:
      - "5000:5000"
    container_name: frontend-redis